name: release
on:
    release:
        types: [created]
jobs:
    npm:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - name: Set Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: yarn install

            - name: Publish to registry
              run: yarn release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
